include theos/makefiles/common.mk

APPLICATION_NAME = HideMyXUninstaller
HideMyXUninstaller_FILES = main.m HideMyXUninstallerApplication.mm RootViewController.mm
HideMyXUninstaller_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
