include theos/makefiles/common.mk

APPLICATION_NAME = HideMyX
HideMyX_FILES = main.m HideMyXApplication.mm RootViewController.mm
HideMyX_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
